export default {
  players: [
    { cubes: 12, discs: 10, symbol: 'alpha' },
    { cubes: 12, discs: 10, symbol: 'beta' },
    { cubes: 12, discs: 10, symbol: 'gamma' },
    { cubes: 12, discs: 10, symbol: 'delta' },
    { cubes: 12, discs: 10, symbol: 'epsilon' },
  ],
  structures: [
    { type: 'shack', colour: 'black' },
    { type: 'shack', colour: 'white' },
    { type: 'shack', colour: 'green' },
    { type: 'shack', colour: 'blue' },
    { type: 'stone', colour: 'black' },
    { type: 'stone', colour: 'white' },
    { type: 'stone', colour: 'green' },
    { type: 'stone', colour: 'blue' },
  ],
  board: [
    {
      anchor: true,
      tile: 0,
      coordinates: { x: 0, y: 0, z: 0 },
      terrain: 'water',
    },
    {
      tile: 0,
      coordinates: { x: 0, y: 1, z: -1 },
      terrain: 'swamp',
    },
    {
      tile: 0,
      coordinates: { x: 0, y: 2, z: -2 },
      terrain: 'swamp',
    },
    {
      tile: 0,
      coordinates: { x: 1, y: 0, z: -1 },
      terrain: 'water',
    },
    {
      tile: 0,
      coordinates: { x: 1, y: 1, z: -2 },
      terrain: 'swamp',
    },
    {
      tile: 0,
      coordinates: { x: 1, y: 2, z: -3 },
      terrain: 'swamp',
    },
    {
      tile: 0,
      coordinates: { x: 2, y: -1, z: -1 },
      terrain: 'water',
    },
    {
      tile: 0,
      coordinates: { x: 2, y: 0, z: -2 },
      terrain: 'water',
    },
    {
      tile: 0,
      coordinates: { x: 2, y: 1, z: -3 },
      terrain: 'desert',
    },
    {
      tile: 0,
      coordinates: { x: 3, y: -1, z: -2 },
      terrain: 'water',
    },
    {
      tile: 0,
      coordinates: { x: 3, y: 0, z: -3 },
      terrain: 'desert',
    },
    {
      tile: 0,
      coordinates: { x: 3, y: 1, z: -4 },
      terrain: 'desert',
      territory: 'bear',
    },
    {
      tile: 0,
      coordinates: { x: 4, y: -2, z: -2 },
      terrain: 'forest',
    },
    {
      tile: 0,
      coordinates: { x: 4, y: -1, z: -3 },
      terrain: 'forest',
    },
    {
      tile: 0,
      coordinates: { x: 4, y: 0, z: -4 },
      terrain: 'desert',
      territory: 'bear',
    },
    {
      tile: 0,
      coordinates: { x: 5, y: -2, z: -3 },
      terrain: 'forest',
    },
    {
      tile: 0,
      coordinates: { x: 5, y: -1, z: -4 },
      terrain: 'forest',
    },
    {
      anchor: true,
      tile: 0,
      coordinates: { x: 5, y: 0, z: -5 },
      terrain: 'forest',
      territory: 'bear',
    },
    {
      tile: 1,
      coordinates: { x: 6, y: -3, z: -3 },
      terrain: 'swamp',
      territory: 'cougar',
    },
    {
      tile: 1,
      coordinates: { x: 6, y: -2, z: -4 },
      terrain: 'swamp',
    },
    {
      tile: 1,
      coordinates: { x: 6, y: -1, z: -5 },
      terrain: 'swamp',
    },
    {
      tile: 1,
      coordinates: { x: 7, y: -3, z: -4 },
      terrain: 'forest',
      territory: 'cougar',
    },
    {
      tile: 1,
      coordinates: { x: 7, y: -2, z: -5 },
      terrain: 'swamp',
    },
    {
      tile: 1,
      coordinates: { x: 7, y: -1, z: -6 },
      terrain: 'mountain',
    },
    {
      tile: 1,
      coordinates: { x: 8, y: -4, z: -4 },
      terrain: 'forest',
      territory: 'cougar',
    },
    {
      tile: 1,
      coordinates: { x: 8, y: -3, z: -5 },
      terrain: 'forest',
    },
    {
      tile: 1,
      coordinates: { x: 8, y: -2, z: -6 },
      terrain: 'mountain',
    },
    {
      tile: 1,
      coordinates: { x: 9, y: -4, z: -5 },
      terrain: 'forest',
    },
    {
      tile: 1,
      coordinates: { x: 9, y: -3, z: -6 },
      terrain: 'desert',
    },
    {
      tile: 1,
      coordinates: { x: 9, y: -2, z: -7 },
      terrain: 'mountain',
    },
    {
      tile: 1,
      coordinates: { x: 10, y: -5, z: -5 },
      terrain: 'forest',
    },
    {
      tile: 1,
      coordinates: { x: 10, y: -4, z: -6 },
      terrain: 'desert',
    },
    {
      tile: 1,
      coordinates: { x: 10, y: -3, z: -7 },
      terrain: 'mountain',
    },
    {
      tile: 1,
      coordinates: { x: 11, y: -5, z: -6 },
      terrain: 'forest',
    },
    {
      tile: 1,
      coordinates: { x: 11, y: -4, z: -7 },
      terrain: 'desert',
    },
    {
      tile: 1,
      coordinates: { x: 11, y: -3, z: -8 },
      terrain: 'desert',
    },
    {
      anchor: true,
      tile: 2,
      coordinates: { x: 0, y: 3, z: -3 },
      terrain: 'swamp',
    },
    {
      tile: 2,
      coordinates: { x: 0, y: 4, z: -4 },
      terrain: 'swamp',
      territory: 'cougar',
    },
    {
      tile: 2,
      coordinates: { x: 0, y: 5, z: -5 },
      terrain: 'mountain',
      territory: 'cougar',
    },
    {
      tile: 2,
      coordinates: { x: 1, y: 3, z: -4 },
      terrain: 'swamp',
    },
    {
      tile: 2,
      coordinates: { x: 1, y: 4, z: -5 },
      terrain: 'swamp',
      territory: 'cougar',
    },
    {
      tile: 2,
      coordinates: { x: 1, y: 5, z: -6 },
      terrain: 'mountain',
    },
    {
      tile: 2,
      coordinates: { x: 2, y: 2, z: -4 },
      terrain: 'forest',
    },
    {
      tile: 2,
      coordinates: { x: 2, y: 3, z: -5 },
      terrain: 'forest',
    },
    {
      tile: 2,
      coordinates: { x: 2, y: 4, z: -6 },
      terrain: 'mountain',
    },
    {
      tile: 2,
      coordinates: { x: 3, y: 2, z: -5 },
      terrain: 'forest',
    },
    {
      tile: 2,
      coordinates: { x: 3, y: 3, z: -6 },
      terrain: 'mountain',
    },
    {
      tile: 2,
      coordinates: { x: 3, y: 4, z: -7 },
      terrain: 'mountain',
    },
    {
      tile: 2,
      coordinates: { x: 4, y: 1, z: -5 },
      terrain: 'forest',
    },
    {
      tile: 2,
      coordinates: { x: 4, y: 2, z: -6 },
      terrain: 'water',
    },
    {
      tile: 2,
      coordinates: { x: 4, y: 3, z: -7 },
      terrain: 'water',
    },
    {
      tile: 2,
      coordinates: { x: 5, y: 1, z: -6 },
      terrain: 'water',
    },
    {
      tile: 2,
      coordinates: { x: 5, y: 2, z: -7 },
      terrain: 'water',
    },
    {
      tile: 2,
      coordinates: { x: 5, y: 3, z: -8 },
      terrain: 'water',
    },
    {
      anchor: true,
      tile: 3,
      coordinates: { x: 6, y: 0, z: -6 },
      terrain: 'desert',
    },
    {
      tile: 3,
      coordinates: { x: 6, y: 1, z: -7 },
      terrain: 'desert',
    },
    {
      tile: 3,
      coordinates: { x: 6, y: 2, z: -8 },
      terrain: 'desert',
    },
    {
      tile: 3,
      coordinates: { x: 7, y: 0, z: -7 },
      terrain: 'desert',
    },
    {
      tile: 3,
      coordinates: { x: 7, y: 1, z: -8 },
      terrain: 'desert',
    },
    {
      tile: 3,
      coordinates: { x: 7, y: 2, z: -9 },
      terrain: 'desert',
    },
    {
      tile: 3,
      coordinates: { x: 8, y: -1, z: -7 },
      terrain: 'mountain',
    },
    {
      tile: 3,
      coordinates: { x: 8, y: 0, z: -8 },
      terrain: 'mountain',
    },
    {
      tile: 3,
      coordinates: { x: 8, y: 1, z: -9 },
      terrain: 'desert',
    },
    {
      tile: 3,
      coordinates: { x: 9, y: -1, z: -8 },
      terrain: 'mountain',
    },
    {
      tile: 3,
      coordinates: { x: 9, y: 0, z: -9 },
      terrain: 'water',
    },
    {
      tile: 3,
      coordinates: { x: 9, y: 1, z: -10 },
      terrain: 'forest',
    },
    {
      tile: 3,
      coordinates: { x: 10, y: -2, z: -8 },
      terrain: 'mountain',
    },
    {
      tile: 3,
      coordinates: { x: 10, y: -1, z: -9 },
      terrain: 'water',
    },
    {
      tile: 3,
      coordinates: { x: 10, y: 0, z: -10 },
      terrain: 'forest',
    },
    {
      tile: 3,
      coordinates: { x: 11, y: -2, z: -9 },
      terrain: 'mountain',
    },
    {
      tile: 3,
      coordinates: { x: 11, y: -1, z: -10 },
      terrain: 'water',
      territory: 'cougar',
    },
    {
      tile: 3,
      coordinates: { x: 11, y: 0, z: -11 },
      terrain: 'forest',
      territory: 'cougar',
    },
    {
      anchor: true,
      tile: 4,
      coordinates: { x: 0, y: 6, z: -6 },
      terrain: 'swamp',
    },
    {
      tile: 4,
      coordinates: { x: 0, y: 7, z: -7 },
      terrain: 'swamp',
    },
    {
      tile: 4,
      coordinates: { x: 0, y: 8, z: -8 },
      terrain: 'desert',
    },
    {
      tile: 4,
      coordinates: { x: 1, y: 6, z: -7 },
      terrain: 'swamp',
    },
    {
      tile: 4,
      coordinates: { x: 1, y: 7, z: -8 },
      terrain: 'desert',
    },
    {
      tile: 4,
      coordinates: { x: 1, y: 8, z: -9 },
      terrain: 'desert',
    },
    {
      tile: 4,
      coordinates: { x: 2, y: 5, z: -7 },
      terrain: 'swamp',
    },
    {
      tile: 4,
      coordinates: { x: 2, y: 6, z: -8 },
      terrain: 'desert',
    },
    {
      tile: 4,
      coordinates: { x: 2, y: 7, z: -9 },
      terrain: 'water',
    },
    {
      tile: 4,
      coordinates: { x: 3, y: 5, z: -8 },
      terrain: 'mountain',
    },
    {
      tile: 4,
      coordinates: { x: 3, y: 6, z: -9 },
      terrain: 'water',
    },
    {
      tile: 4,
      coordinates: { x: 3, y: 7, z: -10 },
      terrain: 'water',
    },
    {
      tile: 4,
      coordinates: { x: 4, y: 4, z: -8 },
      terrain: 'mountain',
    },
    {
      tile: 4,
      coordinates: { x: 4, y: 5, z: -9 },
      terrain: 'mountain',
    },
    {
      tile: 4,
      coordinates: { x: 4, y: 6, z: -10 },
      terrain: 'water',
      territory: 'bear',
    },
    {
      tile: 4,
      coordinates: { x: 5, y: 4, z: -9 },
      terrain: 'mountain',
    },
    {
      tile: 4,
      coordinates: { x: 5, y: 5, z: -10 },
      terrain: 'mountain',
      territory: 'bear',
    },
    {
      tile: 4,
      coordinates: { x: 5, y: 6, z: -11 },
      terrain: 'water',
      territory: 'bear',
    },
    {
      anchor: true,
      tile: 5,
      coordinates: { x: 6, y: 3, z: -9 },
      terrain: 'desert',
      territory: 'bear',
    },
    {
      tile: 5,
      coordinates: { x: 6, y: 4, z: -10 },
      terrain: 'mountain',
      territory: 'bear',
    },
    {
      tile: 5,
      coordinates: { x: 6, y: 5, z: -11 },
      terrain: 'mountain',
    },
    {
      tile: 5,
      coordinates: { x: 7, y: 3, z: -10 },
      terrain: 'desert',
    },
    {
      tile: 5,
      coordinates: { x: 7, y: 4, z: -11 },
      terrain: 'mountain',
    },
    {
      tile: 5,
      coordinates: { x: 7, y: 5, z: -12 },
      terrain: 'water',
    },
    {
      tile: 5,
      coordinates: { x: 8, y: 2, z: -10 },
      terrain: 'swamp',
    },
    {
      tile: 5,
      coordinates: { x: 8, y: 3, z: -11 },
      terrain: 'swamp',
    },
    {
      tile: 5,
      coordinates: { x: 8, y: 4, z: -12 },
      terrain: 'water',
    },
    {
      tile: 5,
      coordinates: { x: 9, y: 2, z: -11 },
      terrain: 'swamp',
    },
    {
      tile: 5,
      coordinates: { x: 9, y: 3, z: -12 },
      terrain: 'swamp',
    },
    {
      tile: 5,
      coordinates: { x: 9, y: 4, z: -13 },
      terrain: 'water',
    },
    {
      tile: 5,
      coordinates: { x: 10, y: 1, z: -11 },
      terrain: 'swamp',
    },
    {
      tile: 5,
      coordinates: { x: 10, y: 2, z: -12 },
      terrain: 'forest',
    },
    {
      tile: 5,
      coordinates: { x: 10, y: 3, z: -13 },
      terrain: 'water',
    },
    {
      tile: 5,
      coordinates: { x: 11, y: 1, z: -12 },
      terrain: 'forest',
    },
    {
      tile: 5,
      coordinates: { x: 11, y: 2, z: -13 },
      terrain: 'forest',
    },
    {
      tile: 5,
      coordinates: { x: 11, y: 3, z: -14 },
      terrain: 'forest',
    },
  ],
};
