export default [
  {
    within: 0,
    type: 'terrain',
    value: ['forest', 'desert'],
    text: 'On forest or desert',
    inverted: false,
  },
  {
    within: 0,
    type: 'terrain',
    value: ['forest', 'water'],
    text: 'On forest or water',
    inverted: false,
  },
  {
    within: 0,
    type: 'terrain',
    value: ['forest', 'swamp'],
    text: 'On forest or swamp',
    inverted: false,
  },
  {
    within: 0,
    type: 'terrain',
    value: ['forest', 'mountain'],
    text: 'On forest or mountain',
    inverted: false,
  },
  {
    within: 0,
    type: 'terrain',
    value: ['desert', 'water'],
    text: 'On desert or water',
    inverted: false,
  },
  {
    within: 0,
    type: 'terrain',
    value: ['desert', 'swamp'],
    text: 'On desert or swamp',
    inverted: false,
  },
  {
    within: 0,
    type: 'terrain',
    value: ['desert', 'mountain'],
    text: 'On desert or mountain',
    inverted: false,
  },
  {
    within: 0,
    type: 'terrain',
    value: ['water', 'swamp'],
    text: 'On water or swamp',
    inverted: false,
  },
  {
    within: 0,
    type: 'terrain',
    value: ['water', 'mountain'],
    text: 'On water or mountain',
    inverted: false,
  },
  {
    within: 0,
    type: 'terrain',
    value: ['swamp', 'mountain'],
    text: 'On swamp or mountain',
    inverted: false,
  },
  {
    within: 1,
    type: 'terrain',
    value: ['forest'],
    text: 'Within 1 space of forest',
    inverted: false,
  },
  {
    within: 1,
    type: 'terrain',
    value: ['desert'],
    text: 'Within 1 space of desert',
    inverted: false,
  },
  {
    within: 1,
    type: 'terrain',
    value: ['swamp'],
    text: 'Within 1 space of swamp',
    inverted: false,
  },
  {
    within: 1,
    type: 'terrain',
    value: ['mountain'],
    text: 'Within 1 space of mountain',
    inverted: false,
  },
  {
    within: 1,
    type: 'terrain',
    value: ['water'],
    text: 'Within 1 space of water',
    inverted: false,
  },
  {
    within: 1,
    type: 'territory',
    value: ['bear', 'cougar'],
    text: 'Within 1 space of either animal territory',
    inverted: false,
  },
  {
    within: 2,
    type: 'structure',
    value: ['stone'],
    text: 'Within 2 spaces of a standing stone',
    inverted: false,
  },
  {
    within: 2,
    type: 'structure',
    value: ['shack'],
    text: 'Within 2 spaces of an abandoned shack',
    inverted: false,
  },
  {
    within: 2,
    type: 'territory',
    value: ['bear'],
    text: 'Within 2 spaces of bear territory',
    inverted: false,
  },
  {
    within: 2,
    type: 'territory',
    value: ['cougar'],
    text: 'Within 2 spaces of cougar territory',
    inverted: false,
  },
  {
    within: 3,
    type: 'colour',
    value: ['blue'],
    text: 'Within 3 spaces of a blue structure',
    inverted: false,
  },
  {
    within: 3,
    type: 'colour',
    value: ['white'],
    text: 'Within 3 spaces of a white structure',
    inverted: false,
  },
  {
    within: 3,
    type: 'colour',
    value: ['green'],
    text: 'Within 3 spaces of a green structure',
    inverted: false,
  },
  {
    within: 3,
    type: 'colour',
    value: ['black'],
    text: 'Within 3 spaces of a black structure',
    inverted: false,
  },
  {
    within: 0,
    type: 'terrain',
    value: ['forest', 'desert'],
    text: 'Not on forest or desert',
    inverted: true,
  },
  {
    within: 0,
    type: 'terrain',
    value: ['forest', 'water'],
    text: 'Not on forest or water',
    inverted: true,
  },
  {
    within: 0,
    type: 'terrain',
    value: ['forest', 'swamp'],
    text: 'Not on forest or swamp',
    inverted: true,
  },
  {
    within: 0,
    type: 'terrain',
    value: ['forest', 'mountain'],
    text: 'Not on forest or mountain',
    inverted: true,
  },
  {
    within: 0,
    type: 'terrain',
    value: ['desert', 'water'],
    text: 'Not on desert or water',
    inverted: true,
  },
  {
    within: 0,
    type: 'terrain',
    value: ['desert', 'swamp'],
    text: 'Not on desert or swamp',
    inverted: true,
  },
  {
    within: 0,
    type: 'terrain',
    value: ['desert', 'mountain'],
    text: 'Not on desert or mountain',
    inverted: true,
  },
  {
    within: 0,
    type: 'terrain',
    value: ['water', 'swamp'],
    text: 'Not on water or swamp',
    inverted: true,
  },
  {
    within: 0,
    type: 'terrain',
    value: ['water', 'mountain'],
    text: 'Not on water or mountain',
    inverted: true,
  },
  {
    within: 0,
    type: 'terrain',
    value: ['swamp', 'mountain'],
    text: 'Not on swamp or mountain',
    inverted: true,
  },
  {
    within: 1,
    type: 'terrain',
    value: ['forest'],
    text: 'Not within 1 space of forest',
    inverted: true,
  },
  {
    within: 1,
    type: 'terrain',
    value: ['desert'],
    text: 'Not within 1 space of desert',
    inverted: true,
  },
  {
    within: 1,
    type: 'terrain',
    value: ['swamp'],
    text: 'Not within 1 space of swamp',
    inverted: true,
  },
  {
    within: 1,
    type: 'terrain',
    value: ['mountain'],
    text: 'Not within 1 space of mountain',
    inverted: true,
  },
  {
    within: 1,
    type: 'terrain',
    value: ['water'],
    text: 'Not within 1 space of water',
    inverted: true,
  },
  {
    within: 1,
    type: 'territory',
    value: ['bear', 'cougar'],
    text: 'Not within 1 space of either animal territory',
    inverted: true,
  },
  {
    within: 2,
    type: 'structure',
    value: ['stone'],
    text: 'Not within 2 spaces of a standing stone',
    inverted: true,
  },
  {
    within: 2,
    type: 'structure',
    value: ['shack'],
    text: 'Not within 2 spaces of an abandoned shack',
    inverted: true,
  },
  {
    within: 2,
    type: 'territory',
    value: ['bear'],
    text: 'Not within 2 spaces of bear territory',
    inverted: true,
  },
  {
    within: 2,
    type: 'territory',
    value: ['cougar'],
    text: 'Not within 2 spaces of cougar territory',
    inverted: true,
  },
  {
    within: 3,
    type: 'colour',
    value: ['blue'],
    text: 'Not within 3 spaces of a blue structure',
    inverted: true,
  },
  {
    within: 3,
    type: 'colour',
    value: ['white'],
    text: 'Not within 3 spaces of a white structure',
    inverted: true,
  },
  {
    within: 3,
    type: 'colour',
    value: ['green'],
    text: 'Not within 3 spaces of a green structure',
    inverted: true,
  },
  {
    within: 3,
    type: 'colour',
    value: ['black'],
    text: 'Not within 3 spaces of a black structure',
    inverted: true,
  },
];
