export default {
  players: [
    { cubes: 12, discs: 10, symbol: 'alpha' },
    { cubes: 12, discs: 10, symbol: 'beta' },
    { cubes: 12, discs: 10, symbol: 'gamma' },
    { cubes: 12, discs: 10, symbol: 'delta' },
    { cubes: 12, discs: 10, symbol: 'epsilon' },
  ],
  structures: [
    { type: 'shack', colour: 'black' },
    { type: 'shack', colour: 'white' },
    { type: 'shack', colour: 'green' },
    { type: 'shack', colour: 'blue' },
    { type: 'stone', colour: 'black' },
    { type: 'stone', colour: 'white' },
    { type: 'stone', colour: 'green' },
    { type: 'stone', colour: 'blue' },
  ],
  board: [
    {
      anchor: true,
      tile: 0,
      coordinates: { q: 0, r: 0, s: 0 },
      terrain: 'water',
    },
    {
      tile: 0,
      coordinates: { q: 0, r: 1, s: -1 },
      terrain: 'swamp',
    },
    {
      tile: 0,
      coordinates: { q: 0, r: 2, s: -2 },
      terrain: 'swamp',
    },
    {
      tile: 0,
      coordinates: { q: 1, r: 0, s: -1 },
      terrain: 'water',
    },
    {
      tile: 0,
      coordinates: { q: 1, r: 1, s: -2 },
      terrain: 'swamp',
    },
    {
      tile: 0,
      coordinates: { q: 1, r: 2, s: -3 },
      terrain: 'swamp',
    },
    {
      tile: 0,
      coordinates: { q: 2, r: -1, s: -1 },
      terrain: 'water',
    },
    {
      tile: 0,
      coordinates: { q: 2, r: 0, s: -2 },
      terrain: 'water',
    },
    {
      tile: 0,
      coordinates: { q: 2, r: 1, s: -3 },
      terrain: 'desert',
    },
    {
      tile: 0,
      coordinates: { q: 3, r: -1, s: -2 },
      terrain: 'water',
    },
    {
      tile: 0,
      coordinates: { q: 3, r: 0, s: -3 },
      terrain: 'desert',
    },
    {
      tile: 0,
      coordinates: { q: 3, r: 1, s: -4 },
      terrain: 'desert',
      territory: 'bear',
    },
    {
      tile: 0,
      coordinates: { q: 4, r: -2, s: -2 },
      terrain: 'forest',
    },
    {
      tile: 0,
      coordinates: { q: 4, r: -1, s: -3 },
      terrain: 'forest',
    },
    {
      tile: 0,
      coordinates: { q: 4, r: 0, s: -4 },
      terrain: 'desert',
      territory: 'bear',
    },
    {
      tile: 0,
      coordinates: { q: 5, r: -2, s: -3 },
      terrain: 'forest',
    },
    {
      tile: 0,
      coordinates: { q: 5, r: -1, s: -4 },
      terrain: 'forest',
    },
    {
      anchor: true,
      tile: 0,
      coordinates: { q: 5, r: 0, s: -5 },
      terrain: 'forest',
      territory: 'bear',
    },
    {
      tile: 1,
      coordinates: { q: 6, r: -3, s: -3 },
      terrain: 'swamp',
      territory: 'cougar',
    },
    {
      tile: 1,
      coordinates: { q: 6, r: -2, s: -4 },
      terrain: 'swamp',
    },
    {
      tile: 1,
      coordinates: { q: 6, r: -1, s: -5 },
      terrain: 'swamp',
    },
    {
      tile: 1,
      coordinates: { q: 7, r: -3, s: -4 },
      terrain: 'forest',
      territory: 'cougar',
    },
    {
      tile: 1,
      coordinates: { q: 7, r: -2, s: -5 },
      terrain: 'swamp',
    },
    {
      tile: 1,
      coordinates: { q: 7, r: -1, s: -6 },
      terrain: 'mountain',
    },
    {
      tile: 1,
      coordinates: { q: 8, r: -4, s: -4 },
      terrain: 'forest',
      territory: 'cougar',
    },
    {
      tile: 1,
      coordinates: { q: 8, r: -3, s: -5 },
      terrain: 'forest',
    },
    {
      tile: 1,
      coordinates: { q: 8, r: -2, s: -6 },
      terrain: 'mountain',
    },
    {
      tile: 1,
      coordinates: { q: 9, r: -4, s: -5 },
      terrain: 'forest',
    },
    {
      tile: 1,
      coordinates: { q: 9, r: -3, s: -6 },
      terrain: 'desert',
    },
    {
      tile: 1,
      coordinates: { q: 9, r: -2, s: -7 },
      terrain: 'mountain',
    },
    {
      tile: 1,
      coordinates: { q: 10, r: -5, s: -5 },
      terrain: 'forest',
    },
    {
      tile: 1,
      coordinates: { q: 10, r: -4, s: -6 },
      terrain: 'desert',
    },
    {
      tile: 1,
      coordinates: { q: 10, r: -3, s: -7 },
      terrain: 'mountain',
    },
    {
      tile: 1,
      coordinates: { q: 11, r: -5, s: -6 },
      terrain: 'forest',
    },
    {
      tile: 1,
      coordinates: { q: 11, r: -4, s: -7 },
      terrain: 'desert',
    },
    {
      tile: 1,
      coordinates: { q: 11, r: -3, s: -8 },
      terrain: 'desert',
    },
    {
      anchor: true,
      tile: 2,
      coordinates: { q: 0, r: 3, s: -3 },
      terrain: 'swamp',
    },
    {
      tile: 2,
      coordinates: { q: 0, r: 4, s: -4 },
      terrain: 'swamp',
      territory: 'cougar',
    },
    {
      tile: 2,
      coordinates: { q: 0, r: 5, s: -5 },
      terrain: 'mountain',
      territory: 'cougar',
    },
    {
      tile: 2,
      coordinates: { q: 1, r: 3, s: -4 },
      terrain: 'swamp',
    },
    {
      tile: 2,
      coordinates: { q: 1, r: 4, s: -5 },
      terrain: 'swamp',
      territory: 'cougar',
    },
    {
      tile: 2,
      coordinates: { q: 1, r: 5, s: -6 },
      terrain: 'mountain',
    },
    {
      tile: 2,
      coordinates: { q: 2, r: 2, s: -4 },
      terrain: 'forest',
    },
    {
      tile: 2,
      coordinates: { q: 2, r: 3, s: -5 },
      terrain: 'forest',
    },
    {
      tile: 2,
      coordinates: { q: 2, r: 4, s: -6 },
      terrain: 'mountain',
    },
    {
      tile: 2,
      coordinates: { q: 3, r: 2, s: -5 },
      terrain: 'forest',
    },
    {
      tile: 2,
      coordinates: { q: 3, r: 3, s: -6 },
      terrain: 'mountain',
    },
    {
      tile: 2,
      coordinates: { q: 3, r: 4, s: -7 },
      terrain: 'mountain',
    },
    {
      tile: 2,
      coordinates: { q: 4, r: 1, s: -5 },
      terrain: 'forest',
    },
    {
      tile: 2,
      coordinates: { q: 4, r: 2, s: -6 },
      terrain: 'water',
    },
    {
      tile: 2,
      coordinates: { q: 4, r: 3, s: -7 },
      terrain: 'water',
    },
    {
      tile: 2,
      coordinates: { q: 5, r: 1, s: -6 },
      terrain: 'water',
    },
    {
      tile: 2,
      coordinates: { q: 5, r: 2, s: -7 },
      terrain: 'water',
    },
    {
      tile: 2,
      coordinates: { q: 5, r: 3, s: -8 },
      terrain: 'water',
    },
    {
      anchor: true,
      tile: 3,
      coordinates: { q: 6, r: 0, s: -6 },
      terrain: 'desert',
    },
    {
      tile: 3,
      coordinates: { q: 6, r: 1, s: -7 },
      terrain: 'desert',
    },
    {
      tile: 3,
      coordinates: { q: 6, r: 2, s: -8 },
      terrain: 'desert',
    },
    {
      tile: 3,
      coordinates: { q: 7, r: 0, s: -7 },
      terrain: 'desert',
    },
    {
      tile: 3,
      coordinates: { q: 7, r: 1, s: -8 },
      terrain: 'desert',
    },
    {
      tile: 3,
      coordinates: { q: 7, r: 2, s: -9 },
      terrain: 'desert',
    },
    {
      tile: 3,
      coordinates: { q: 8, r: -1, s: -7 },
      terrain: 'mountain',
    },
    {
      tile: 3,
      coordinates: { q: 8, r: 0, s: -8 },
      terrain: 'mountain',
    },
    {
      tile: 3,
      coordinates: { q: 8, r: 1, s: -9 },
      terrain: 'desert',
    },
    {
      tile: 3,
      coordinates: { q: 9, r: -1, s: -8 },
      terrain: 'mountain',
    },
    {
      tile: 3,
      coordinates: { q: 9, r: 0, s: -9 },
      terrain: 'water',
    },
    {
      tile: 3,
      coordinates: { q: 9, r: 1, s: -10 },
      terrain: 'forest',
    },
    {
      tile: 3,
      coordinates: { q: 10, r: -2, s: -8 },
      terrain: 'mountain',
    },
    {
      tile: 3,
      coordinates: { q: 10, r: -1, s: -9 },
      terrain: 'water',
    },
    {
      tile: 3,
      coordinates: { q: 10, r: 0, s: -10 },
      terrain: 'forest',
    },
    {
      tile: 3,
      coordinates: { q: 11, r: -2, s: -9 },
      terrain: 'mountain',
    },
    {
      tile: 3,
      coordinates: { q: 11, r: -1, s: -10 },
      terrain: 'water',
      territory: 'cougar',
    },
    {
      tile: 3,
      coordinates: { q: 11, r: 0, s: -11 },
      terrain: 'forest',
      territory: 'cougar',
    },
    {
      anchor: true,
      tile: 4,
      coordinates: { q: 0, r: 6, s: -6 },
      terrain: 'swamp',
    },
    {
      tile: 4,
      coordinates: { q: 0, r: 7, s: -7 },
      terrain: 'swamp',
    },
    {
      tile: 4,
      coordinates: { q: 0, r: 8, s: -8 },
      terrain: 'desert',
    },
    {
      tile: 4,
      coordinates: { q: 1, r: 6, s: -7 },
      terrain: 'swamp',
    },
    {
      tile: 4,
      coordinates: { q: 1, r: 7, s: -8 },
      terrain: 'desert',
    },
    {
      tile: 4,
      coordinates: { q: 1, r: 8, s: -9 },
      terrain: 'desert',
    },
    {
      tile: 4,
      coordinates: { q: 2, r: 5, s: -7 },
      terrain: 'swamp',
    },
    {
      tile: 4,
      coordinates: { q: 2, r: 6, s: -8 },
      terrain: 'desert',
    },
    {
      tile: 4,
      coordinates: { q: 2, r: 7, s: -9 },
      terrain: 'water',
    },
    {
      tile: 4,
      coordinates: { q: 3, r: 5, s: -8 },
      terrain: 'mountain',
    },
    {
      tile: 4,
      coordinates: { q: 3, r: 6, s: -9 },
      terrain: 'water',
    },
    {
      tile: 4,
      coordinates: { q: 3, r: 7, s: -10 },
      terrain: 'water',
    },
    {
      tile: 4,
      coordinates: { q: 4, r: 4, s: -8 },
      terrain: 'mountain',
    },
    {
      tile: 4,
      coordinates: { q: 4, r: 5, s: -9 },
      terrain: 'mountain',
    },
    {
      tile: 4,
      coordinates: { q: 4, r: 6, s: -10 },
      terrain: 'water',
      territory: 'bear',
    },
    {
      tile: 4,
      coordinates: { q: 5, r: 4, s: -9 },
      terrain: 'mountain',
    },
    {
      tile: 4,
      coordinates: { q: 5, r: 5, s: -10 },
      terrain: 'mountain',
      territory: 'bear',
    },
    {
      tile: 4,
      coordinates: { q: 5, r: 6, s: -11 },
      terrain: 'water',
      territory: 'bear',
    },
    {
      anchor: true,
      tile: 5,
      coordinates: { q: 6, r: 3, s: -9 },
      terrain: 'desert',
      territory: 'bear',
    },
    {
      tile: 5,
      coordinates: { q: 6, r: 4, s: -10 },
      terrain: 'mountain',
      territory: 'bear',
    },
    {
      tile: 5,
      coordinates: { q: 6, r: 5, s: -11 },
      terrain: 'mountain',
    },
    {
      tile: 5,
      coordinates: { q: 7, r: 3, s: -10 },
      terrain: 'desert',
    },
    {
      tile: 5,
      coordinates: { q: 7, r: 4, s: -11 },
      terrain: 'mountain',
    },
    {
      tile: 5,
      coordinates: { q: 7, r: 5, s: -12 },
      terrain: 'water',
    },
    {
      tile: 5,
      coordinates: { q: 8, r: 2, s: -10 },
      terrain: 'swamp',
    },
    {
      tile: 5,
      coordinates: { q: 8, r: 3, s: -11 },
      terrain: 'swamp',
    },
    {
      tile: 5,
      coordinates: { q: 8, r: 4, s: -12 },
      terrain: 'water',
    },
    {
      tile: 5,
      coordinates: { q: 9, r: 2, s: -11 },
      terrain: 'swamp',
    },
    {
      tile: 5,
      coordinates: { q: 9, r: 3, s: -12 },
      terrain: 'swamp',
    },
    {
      tile: 5,
      coordinates: { q: 9, r: 4, s: -13 },
      terrain: 'water',
    },
    {
      tile: 5,
      coordinates: { q: 10, r: 1, s: -11 },
      terrain: 'swamp',
    },
    {
      tile: 5,
      coordinates: { q: 10, r: 2, s: -12 },
      terrain: 'forest',
    },
    {
      tile: 5,
      coordinates: { q: 10, r: 3, s: -13 },
      terrain: 'water',
    },
    {
      tile: 5,
      coordinates: { q: 11, r: 1, s: -12 },
      terrain: 'forest',
    },
    {
      tile: 5,
      coordinates: { q: 11, r: 2, s: -13 },
      terrain: 'forest',
    },
    {
      tile: 5,
      coordinates: { q: 11, r: 3, s: -14 },
      terrain: 'forest',
    },
  ],
};
