export default {
  players: [
    { cube: 12, disc: 10, colour: 'alpha' },
    { cube: 12, disc: 10, colour: 'beta' },
    { cube: 12, disc: 10, colour: 'gamma' },
    { cube: 12, disc: 10, colour: 'delta' },
    { cube: 12, disc: 10, colour: 'epsilon' },
  ],
  structures: [
    { shack: 1, stone: 1, colour: 'black' },
    { shack: 1, stone: 1, colour: 'white' },
    { shack: 1, stone: 1, colour: 'green' },
    { shack: 1, stone: 1, colour: 'blue' },
  ],
  board: [
    {
      anchor: true,
      tile: 0,
      coordinates: { q: 0, r: 0, s: 0 },
      terrain: 'water',
      structures: [],
      clues: [],
    },
    {
      tile: 0,
      coordinates: { q: 0, r: 1, s: -1 },
      terrain: 'swamp',
      structures: [],
      clues: [],
    },
    {
      tile: 0,
      coordinates: { q: 0, r: 2, s: -2 },
      terrain: 'swamp',
      structures: [],
      clues: [],
    },
    {
      tile: 0,
      coordinates: { q: 1, r: 0, s: -1 },
      terrain: 'water',
      structures: [],
      clues: [],
    },
    {
      tile: 0,
      coordinates: { q: 1, r: 1, s: -2 },
      terrain: 'swamp',
      structures: [],
      clues: [],
    },
    {
      tile: 0,
      coordinates: { q: 1, r: 2, s: -3 },
      terrain: 'swamp',
      structures: [],
      clues: [],
    },
    {
      tile: 0,
      coordinates: { q: 2, r: -1, s: -1 },
      terrain: 'water',
      structures: [],
      clues: [],
    },
    {
      tile: 0,
      coordinates: { q: 2, r: 0, s: -2 },
      terrain: 'water',
      structures: [],
      clues: [],
    },
    {
      tile: 0,
      coordinates: { q: 2, r: 1, s: -3 },
      terrain: 'desert',
      structures: [],
      clues: [],
    },
    {
      tile: 0,
      coordinates: { q: 3, r: -1, s: -2 },
      terrain: 'water',
      structures: [],
      clues: [],
    },
    {
      tile: 0,
      coordinates: { q: 3, r: 0, s: -3 },
      terrain: 'desert',
      structures: [],
      clues: [],
    },
    {
      tile: 0,
      coordinates: { q: 3, r: 1, s: -4 },
      terrain: 'desert',
      territory: 'bear',
      structures: [],
      clues: [],
    },
    {
      tile: 0,
      coordinates: { q: 4, r: -2, s: -2 },
      terrain: 'forest',
      structures: [],
      clues: [],
    },
    {
      tile: 0,
      coordinates: { q: 4, r: -1, s: -3 },
      terrain: 'forest',
      structures: [],
      clues: [],
    },
    {
      tile: 0,
      coordinates: { q: 4, r: 0, s: -4 },
      terrain: 'desert',
      territory: 'bear',
      structures: [],
      clues: [],
    },
    {
      tile: 0,
      coordinates: { q: 5, r: -2, s: -3 },
      terrain: 'forest',
      structures: [],
      clues: [],
    },
    {
      tile: 0,
      coordinates: { q: 5, r: -1, s: -4 },
      terrain: 'forest',
      structures: [],
      clues: [],
    },
    {
      tile: 0,
      coordinates: { q: 5, r: 0, s: -5 },
      terrain: 'forest',
      territory: 'bear',
      structures: [],
      clues: [],
    },
    {
      anchor: true,
      tile: 1,
      coordinates: { q: 6, r: -3, s: -3 },
      terrain: 'swamp',
      territory: 'cougar',
      structures: [],
      clues: [],
    },
    {
      tile: 1,
      coordinates: { q: 6, r: -2, s: -4 },
      terrain: 'swamp',
      structures: [],
      clues: [],
    },
    {
      tile: 1,
      coordinates: { q: 6, r: -1, s: -5 },
      terrain: 'swamp',
      structures: [],
      clues: [],
    },
    {
      tile: 1,
      coordinates: { q: 7, r: -3, s: -4 },
      terrain: 'forest',
      territory: 'cougar',
      structures: [],
      clues: [],
    },
    {
      tile: 1,
      coordinates: { q: 7, r: -2, s: -5 },
      terrain: 'swamp',
      structures: [],
      clues: [],
    },
    {
      tile: 1,
      coordinates: { q: 7, r: -1, s: -6 },
      terrain: 'mountain',
      structures: [],
      clues: [],
    },
    {
      tile: 1,
      coordinates: { q: 8, r: -4, s: -4 },
      terrain: 'forest',
      territory: 'cougar',
      structures: [],
      clues: [],
    },
    {
      tile: 1,
      coordinates: { q: 8, r: -3, s: -5 },
      terrain: 'forest',
      structures: [],
      clues: [],
    },
    {
      tile: 1,
      coordinates: { q: 8, r: -2, s: -6 },
      terrain: 'mountain',
      structures: [],
      clues: [],
    },
    {
      tile: 1,
      coordinates: { q: 9, r: -4, s: -5 },
      terrain: 'forest',
      structures: [],
      clues: [],
    },
    {
      tile: 1,
      coordinates: { q: 9, r: -3, s: -6 },
      terrain: 'desert',
      structures: [],
      clues: [],
    },
    {
      tile: 1,
      coordinates: { q: 9, r: -2, s: -7 },
      terrain: 'mountain',
      structures: [],
      clues: [],
    },
    {
      tile: 1,
      coordinates: { q: 10, r: -5, s: -5 },
      terrain: 'forest',
      structures: [],
      clues: [],
    },
    {
      tile: 1,
      coordinates: { q: 10, r: -4, s: -6 },
      terrain: 'desert',
      structures: [],
      clues: [],
    },
    {
      tile: 1,
      coordinates: { q: 10, r: -3, s: -7 },
      terrain: 'mountain',
      structures: [],
      clues: [],
    },
    {
      tile: 1,
      coordinates: { q: 11, r: -5, s: -6 },
      terrain: 'forest',
      structures: [],
      clues: [],
    },
    {
      tile: 1,
      coordinates: { q: 11, r: -4, s: -7 },
      terrain: 'desert',
      structures: [],
      clues: [],
    },
    {
      tile: 1,
      coordinates: { q: 11, r: -3, s: -8 },
      terrain: 'desert',
      structures: [],
      clues: [],
    },
    {
      anchor: true,
      tile: 2,
      coordinates: { q: 0, r: 3, s: -3 },
      terrain: 'swamp',
      structures: [],
      clues: [],
    },
    {
      tile: 2,
      coordinates: { q: 0, r: 4, s: -4 },
      terrain: 'swamp',
      territory: 'cougar',
      structures: [],
      clues: [],
    },
    {
      tile: 2,
      coordinates: { q: 0, r: 5, s: -5 },
      terrain: 'mountain',
      territory: 'cougar',
      structures: [],
      clues: [],
    },
    {
      tile: 2,
      coordinates: { q: 1, r: 3, s: -4 },
      terrain: 'swamp',
      structures: [],
      clues: [],
    },
    {
      tile: 2,
      coordinates: { q: 1, r: 4, s: -5 },
      terrain: 'swamp',
      territory: 'cougar',
      structures: [],
      clues: [],
    },
    {
      tile: 2,
      coordinates: { q: 1, r: 5, s: -6 },
      terrain: 'mountain',
      structures: [],
      clues: [],
    },
    {
      tile: 2,
      coordinates: { q: 2, r: 2, s: -4 },
      terrain: 'forest',
      structures: [],
      clues: [],
    },
    {
      tile: 2,
      coordinates: { q: 2, r: 3, s: -5 },
      terrain: 'forest',
      structures: [],
      clues: [],
    },
    {
      tile: 2,
      coordinates: { q: 2, r: 4, s: -6 },
      terrain: 'mountain',
      structures: [],
      clues: [],
    },
    {
      tile: 2,
      coordinates: { q: 3, r: 2, s: -5 },
      terrain: 'forest',
      structures: [],
      clues: [],
    },
    {
      tile: 2,
      coordinates: { q: 3, r: 3, s: -6 },
      terrain: 'mountain',
      structures: [],
      clues: [],
    },
    {
      tile: 2,
      coordinates: { q: 3, r: 4, s: -7 },
      terrain: 'mountain',
      structures: [],
      clues: [],
    },
    {
      tile: 2,
      coordinates: { q: 4, r: 1, s: -5 },
      terrain: 'forest',
      structures: [],
      clues: [],
    },
    {
      tile: 2,
      coordinates: { q: 4, r: 2, s: -6 },
      terrain: 'water',
      structures: [],
      clues: [],
    },
    {
      tile: 2,
      coordinates: { q: 4, r: 3, s: -7 },
      terrain: 'water',
      structures: [],
      clues: [],
    },
    {
      tile: 2,
      coordinates: { q: 5, r: 1, s: -6 },
      terrain: 'water',
      structures: [],
      clues: [],
    },
    {
      tile: 2,
      coordinates: { q: 5, r: 2, s: -7 },
      terrain: 'water',
      structures: [],
      clues: [],
    },
    {
      tile: 2,
      coordinates: { q: 5, r: 3, s: -8 },
      terrain: 'water',
      structures: [],
      clues: [],
    },
    {
      anchor: true,
      tile: 3,
      coordinates: { q: 6, r: 0, s: -6 },
      terrain: 'desert',
      structures: [],
      clues: [],
    },
    {
      tile: 3,
      coordinates: { q: 6, r: 1, s: -7 },
      terrain: 'desert',
      structures: [],
      clues: [],
    },
    {
      tile: 3,
      coordinates: { q: 6, r: 2, s: -8 },
      terrain: 'desert',
      structures: [],
      clues: [],
    },
    {
      tile: 3,
      coordinates: { q: 7, r: 0, s: -7 },
      terrain: 'desert',
      structures: [],
      clues: [],
    },
    {
      tile: 3,
      coordinates: { q: 7, r: 1, s: -8 },
      terrain: 'desert',
      structures: [],
      clues: [],
    },
    {
      tile: 3,
      coordinates: { q: 7, r: 2, s: -9 },
      terrain: 'desert',
      structures: [],
      clues: [],
    },
    {
      tile: 3,
      coordinates: { q: 8, r: -1, s: -7 },
      terrain: 'mountain',
      structures: [],
      clues: [],
    },
    {
      tile: 3,
      coordinates: { q: 8, r: 0, s: -8 },
      terrain: 'mountain',
      structures: [],
      clues: [],
    },
    {
      tile: 3,
      coordinates: { q: 8, r: 1, s: -9 },
      terrain: 'desert',
      structures: [],
      clues: [],
    },
    {
      tile: 3,
      coordinates: { q: 9, r: -1, s: -8 },
      terrain: 'mountain',
      structures: [],
      clues: [],
    },
    {
      tile: 3,
      coordinates: { q: 9, r: 0, s: -9 },
      terrain: 'water',
      structures: [],
      clues: [],
    },
    {
      tile: 3,
      coordinates: { q: 9, r: 1, s: -10 },
      terrain: 'forest',
      structures: [],
      clues: [],
    },
    {
      tile: 3,
      coordinates: { q: 10, r: -2, s: -8 },
      terrain: 'mountain',
      structures: [],
      clues: [],
    },
    {
      tile: 3,
      coordinates: { q: 10, r: -1, s: -9 },
      terrain: 'water',
      structures: [],
      clues: [],
    },
    {
      tile: 3,
      coordinates: { q: 10, r: 0, s: -10 },
      terrain: 'forest',
      structures: [],
      clues: [],
    },
    {
      tile: 3,
      coordinates: { q: 11, r: -2, s: -9 },
      terrain: 'mountain',
      structures: [],
      clues: [],
    },
    {
      tile: 3,
      coordinates: { q: 11, r: -1, s: -10 },
      terrain: 'water',
      territory: 'cougar',
      structures: [],
      clues: [],
    },
    {
      tile: 3,
      coordinates: { q: 11, r: 0, s: -11 },
      terrain: 'forest',
      territory: 'cougar',
      structures: [],
      clues: [],
    },
    {
      anchor: true,
      tile: 4,
      coordinates: { q: 0, r: 6, s: -6 },
      terrain: 'swamp',
      structures: [],
      clues: [],
    },
    {
      tile: 4,
      coordinates: { q: 0, r: 7, s: -7 },
      terrain: 'swamp',
      structures: [],
      clues: [],
    },
    {
      tile: 4,
      coordinates: { q: 0, r: 8, s: -8 },
      terrain: 'desert',
      structures: [],
      clues: [],
    },
    {
      tile: 4,
      coordinates: { q: 1, r: 6, s: -7 },
      terrain: 'swamp',
      structures: [],
      clues: [],
    },
    {
      tile: 4,
      coordinates: { q: 1, r: 7, s: -8 },
      terrain: 'desert',
      structures: [],
      clues: [],
    },
    {
      tile: 4,
      coordinates: { q: 1, r: 8, s: -9 },
      terrain: 'desert',
      structures: [],
      clues: [],
    },
    {
      tile: 4,
      coordinates: { q: 2, r: 5, s: -7 },
      terrain: 'swamp',
      structures: [],
      clues: [],
    },
    {
      tile: 4,
      coordinates: { q: 2, r: 6, s: -8 },
      terrain: 'desert',
      structures: [],
      clues: [],
    },
    {
      tile: 4,
      coordinates: { q: 2, r: 7, s: -9 },
      terrain: 'water',
      structures: [],
      clues: [],
    },
    {
      tile: 4,
      coordinates: { q: 3, r: 5, s: -8 },
      terrain: 'mountain',
      structures: [],
      clues: [],
    },
    {
      tile: 4,
      coordinates: { q: 3, r: 6, s: -9 },
      terrain: 'water',
      structures: [],
      clues: [],
    },
    {
      tile: 4,
      coordinates: { q: 3, r: 7, s: -10 },
      terrain: 'water',
      structures: [],
      clues: [],
    },
    {
      tile: 4,
      coordinates: { q: 4, r: 4, s: -8 },
      terrain: 'mountain',
      structures: [],
      clues: [],
    },
    {
      tile: 4,
      coordinates: { q: 4, r: 5, s: -9 },
      terrain: 'mountain',
      structures: [],
      clues: [],
    },
    {
      tile: 4,
      coordinates: { q: 4, r: 6, s: -10 },
      terrain: 'water',
      territory: 'bear',
      structures: [],
      clues: [],
    },
    {
      tile: 4,
      coordinates: { q: 5, r: 4, s: -9 },
      terrain: 'mountain',
      structures: [],
      clues: [],
    },
    {
      tile: 4,
      coordinates: { q: 5, r: 5, s: -10 },
      terrain: 'mountain',
      territory: 'bear',
      structures: [],
      clues: [],
    },
    {
      tile: 4,
      coordinates: { q: 5, r: 6, s: -11 },
      terrain: 'water',
      territory: 'bear',
      structures: [],
      clues: [],
    },
    {
      anchor: true,
      tile: 5,
      coordinates: { q: 6, r: 3, s: -9 },
      terrain: 'desert',
      territory: 'bear',
      structures: [],
      clues: [],
    },
    {
      tile: 5,
      coordinates: { q: 6, r: 4, s: -10 },
      terrain: 'mountain',
      territory: 'bear',
      structures: [],
      clues: [],
    },
    {
      tile: 5,
      coordinates: { q: 6, r: 5, s: -11 },
      terrain: 'mountain',
      structures: [],
      clues: [],
    },
    {
      tile: 5,
      coordinates: { q: 7, r: 3, s: -10 },
      terrain: 'desert',
      structures: [],
      clues: [],
    },
    {
      tile: 5,
      coordinates: { q: 7, r: 4, s: -11 },
      terrain: 'mountain',
      structures: [],
      clues: [],
    },
    {
      tile: 5,
      coordinates: { q: 7, r: 5, s: -12 },
      terrain: 'water',
      structures: [],
      clues: [],
    },
    {
      tile: 5,
      coordinates: { q: 8, r: 2, s: -10 },
      terrain: 'swamp',
      structures: [],
      clues: [],
    },
    {
      tile: 5,
      coordinates: { q: 8, r: 3, s: -11 },
      terrain: 'swamp',
      structures: [],
      clues: [],
    },
    {
      tile: 5,
      coordinates: { q: 8, r: 4, s: -12 },
      terrain: 'water',
      structures: [],
      clues: [],
    },
    {
      tile: 5,
      coordinates: { q: 9, r: 2, s: -11 },
      terrain: 'swamp',
      structures: [],
      clues: [],
    },
    {
      tile: 5,
      coordinates: { q: 9, r: 3, s: -12 },
      terrain: 'swamp',
      structures: [],
      clues: [],
    },
    {
      tile: 5,
      coordinates: { q: 9, r: 4, s: -13 },
      terrain: 'water',
      structures: [],
      clues: [],
    },
    {
      tile: 5,
      coordinates: { q: 10, r: 1, s: -11 },
      terrain: 'swamp',
      structures: [],
      clues: [],
    },
    {
      tile: 5,
      coordinates: { q: 10, r: 2, s: -12 },
      terrain: 'forest',
      structures: [],
      clues: [],
    },
    {
      tile: 5,
      coordinates: { q: 10, r: 3, s: -13 },
      terrain: 'water',
      structures: [],
      clues: [],
    },
    {
      tile: 5,
      coordinates: { q: 11, r: 1, s: -12 },
      terrain: 'forest',
      structures: [],
      clues: [],
    },
    {
      tile: 5,
      coordinates: { q: 11, r: 2, s: -13 },
      terrain: 'forest',
      structures: [],
      clues: [],
    },
    {
      tile: 5,
      coordinates: { q: 11, r: 3, s: -14 },
      terrain: 'forest',
      structures: [],
      clues: [],
    },
  ],
  ruleset: [
    {
      within: 0,
      type: 'terrain',
      value: ['forest', 'desert'],
      text: 'On forest/desert',
      inverted: false,
    },
    {
      within: 0,
      type: 'terrain',
      value: ['forest', 'water'],
      text: 'On forest/water',
      inverted: false,
    },
    {
      within: 0,
      type: 'terrain',
      value: ['forest', 'swamp'],
      text: 'On forest/swamp',
      inverted: false,
    },
    {
      within: 0,
      type: 'terrain',
      value: ['forest', 'mountain'],
      text: 'On forest/mountain',
      inverted: false,
    },
    {
      within: 0,
      type: 'terrain',
      value: ['desert', 'water'],
      text: 'On desert/water',
      inverted: false,
    },
    {
      within: 0,
      type: 'terrain',
      value: ['desert', 'swamp'],
      text: 'On desert/swamp',
      inverted: false,
    },
    {
      within: 0,
      type: 'terrain',
      value: ['desert', 'mountain'],
      text: 'On desert/mountain',
      inverted: false,
    },
    {
      within: 0,
      type: 'terrain',
      value: ['water', 'swamp'],
      text: 'On water/swamp',
      inverted: false,
    },
    {
      within: 0,
      type: 'terrain',
      value: ['water', 'mountain'],
      text: 'On water/mountain',
      inverted: false,
    },
    {
      within: 0,
      type: 'terrain',
      value: ['swamp', 'mountain'],
      text: 'On swamp/mountain',
      inverted: false,
    },
    {
      within: 1,
      type: 'terrain',
      value: ['forest'],
      text: 'Within 1 of forest',
      inverted: false,
    },
    {
      within: 1,
      type: 'terrain',
      value: ['desert'],
      text: 'Within 1 of desert',
      inverted: false,
    },
    {
      within: 1,
      type: 'terrain',
      value: ['swamp'],
      text: 'Within 1 of swamp',
      inverted: false,
    },
    {
      within: 1,
      type: 'terrain',
      value: ['mountain'],
      text: 'Within 1 of mountain',
      inverted: false,
    },
    {
      within: 1,
      type: 'terrain',
      value: ['water'],
      text: 'Within 1 of water',
      inverted: false,
    },
    {
      within: 1,
      type: 'territory',
      value: ['bear', 'cougar'],
      text: 'Within 1 of bear/cougar',
      inverted: false,
    },
    {
      within: 2,
      type: 'structure',
      value: ['stone'],
      text: 'Within 2 of stone',
      inverted: false,
    },
    {
      within: 2,
      type: 'structure',
      value: ['shack'],
      text: 'Within 2 of shack',
      inverted: false,
    },
    {
      within: 2,
      type: 'territory',
      value: ['bear'],
      text: 'Within 2 of bear',
      inverted: false,
    },
    {
      within: 2,
      type: 'territory',
      value: ['cougar'],
      text: 'Within 2 of cougar',
      inverted: false,
    },
    {
      within: 3,
      type: 'colour',
      value: ['blue'],
      text: 'Within 3 of blue',
      inverted: false,
    },
    {
      within: 3,
      type: 'colour',
      value: ['white'],
      text: 'Within 3 of white',
      inverted: false,
    },
    {
      within: 3,
      type: 'colour',
      value: ['green'],
      text: 'Within 3 of green',
      inverted: false,
    },
    {
      within: 3,
      type: 'colour',
      value: ['black'],
      text: 'Within 3 of black',
      inverted: false,
    },
    {
      within: 0,
      type: 'terrain',
      value: ['forest', 'desert'],
      text: 'Not on forest/desert',
      inverted: true,
    },
    {
      within: 0,
      type: 'terrain',
      value: ['forest', 'water'],
      text: 'Not on forest/water',
      inverted: true,
    },
    {
      within: 0,
      type: 'terrain',
      value: ['forest', 'swamp'],
      text: 'Not on forest/swamp',
      inverted: true,
    },
    {
      within: 0,
      type: 'terrain',
      value: ['forest', 'mountain'],
      text: 'Not on forest/mountain',
      inverted: true,
    },
    {
      within: 0,
      type: 'terrain',
      value: ['desert', 'water'],
      text: 'Not on desert/water',
      inverted: true,
    },
    {
      within: 0,
      type: 'terrain',
      value: ['desert', 'swamp'],
      text: 'Not on desert/swamp',
      inverted: true,
    },
    {
      within: 0,
      type: 'terrain',
      value: ['desert', 'mountain'],
      text: 'Not on desert/mountain',
      inverted: true,
    },
    {
      within: 0,
      type: 'terrain',
      value: ['water', 'swamp'],
      text: 'Not on water/swamp',
      inverted: true,
    },
    {
      within: 0,
      type: 'terrain',
      value: ['water', 'mountain'],
      text: 'Not on water/mountain',
      inverted: true,
    },
    {
      within: 0,
      type: 'terrain',
      value: ['swamp', 'mountain'],
      text: 'Not on swamp/mountain',
      inverted: true,
    },
    {
      within: 1,
      type: 'terrain',
      value: ['forest'],
      text: 'Not within 1 of forest',
      inverted: true,
    },
    {
      within: 1,
      type: 'terrain',
      value: ['desert'],
      text: 'Not within 1 of desert',
      inverted: true,
    },
    {
      within: 1,
      type: 'terrain',
      value: ['swamp'],
      text: 'Not within 1 of swamp',
      inverted: true,
    },
    {
      within: 1,
      type: 'terrain',
      value: ['mountain'],
      text: 'Not within 1 of mountain',
      inverted: true,
    },
    {
      within: 1,
      type: 'terrain',
      value: ['water'],
      text: 'Not within 1 of water',
      inverted: true,
    },
    {
      within: 1,
      type: 'territory',
      value: ['bear', 'cougar'],
      text: 'Not within 1 of bear/cougar',
      inverted: true,
    },
    {
      within: 2,
      type: 'structure',
      value: ['stone'],
      text: 'Not within 2 of stone',
      inverted: true,
    },
    {
      within: 2,
      type: 'structure',
      value: ['shack'],
      text: 'Not within 2 of shack',
      inverted: true,
    },
    {
      within: 2,
      type: 'territory',
      value: ['bear'],
      text: 'Not within 2 of bear',
      inverted: true,
    },
    {
      within: 2,
      type: 'territory',
      value: ['cougar'],
      text: 'Not within 2 of cougar',
      inverted: true,
    },
    {
      within: 3,
      type: 'colour',
      value: ['blue'],
      text: 'Not within 3 of blue',
      inverted: true,
    },
    {
      within: 3,
      type: 'colour',
      value: ['white'],
      text: 'Not within 3 of white',
      inverted: true,
    },
    {
      within: 3,
      type: 'colour',
      value: ['green'],
      text: 'Not within 3 of green',
      inverted: true,
    },
    {
      within: 3,
      type: 'colour',
      value: ['black'],
      text: 'Not within 3 of black',
      inverted: true,
    },
  ],
};
